var str = prompt ("Your Name")
console.log(str)
var str = prompt ("How old a u")
console.log(str)
var str = +prompt ("Your answer 2+2= ")
console.log("Answer1 "+" 2+2=" +(2+2) + " Your answer=" + str)
var str = +prompt ("Your Answer 40-2= ")
console.log("Answer2 "+" 40-2=" +(40-2) + " Your answer=" + str)
var str = +prompt ("Your answer 10*2= ")
console.log("Answer3 "+" 10*2=" +(10*2) + " Your answer=" + str)
var str = +prompt("Your Answer 20/2= ")
console.log("Answer4 "+" 20/2=" +(20/2) + " Your Answer=" + str)